components:
  parameters:
    fechaAplicacion:
      name: fechaAplicacion
      in: query
      required: true
      description: Fecha de aplicación de la tarifa
      schema:
        type: string
        format: date-time

    idProducto:
      name: idProducto
      in: query
      required: true
      description: Identificador del producto
      schema:
        type: string

    idCadena:
      name: idCadena
      in: query
      required: true
      description: Identificador de la cadena
      schema:
        type: string

