# Configuración del servidor
server.port=8085
server.servlet.context-path=/demo-bcnc

# Usa base de datos en memoria
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostrar consola H2 en navegador (opcional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Borrar y crear tablas cada vez que se arranca
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Mostrar SQL en consola (opcional para debug)
spring.jpa.show-sql=true




