-- Crear usuario admin con contraseña admin
CREATE USER IF NOT EXISTS admin PASSWORD 'admin';

-- Otorgar todos los privilegios al usuario admin sobre el esquema PUBLIC
GRANT ALL ON SCHEMA PUBLIC TO admin;

CREATE TABLE GRUPOS (
    BRAND_ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

-- Insertar datos en la tabla GRUPOS
INSERT INTO GRUPOS (BRAND_ID, NAME) VALUES
(1, 'ZARA');

-- Crear la tabla PRODUCTO
CREATE TABLE PRODUCTO (
    ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255)
);
INSERT INTO PRODUCTO (ID, NAME, DESCRIPTION) VALUES
(0, 'Camiseta Zara', 'Descripción del producto demo');
INSERT INTO PRODUCTO (ID, NAME, DESCRIPTION) VALUES
(1, 'Pantalon Zara', 'Descripción del producto demo');



CREATE TABLE PRICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY BOOLEAN NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CURR VARCHAR(3) NOT NULL
);


ALTER TABLE PRICES
ADD CONSTRAINT FK_PRICES_GRUPOS
FOREIGN KEY (BRAND_ID) REFERENCES GRUPOS (BRAND_ID);

ALTER TABLE PRICES
ADD CONSTRAINT FK_PRICES_PRODUCTO
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTO (ID);

INSERT INTO PRICES (BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR) VALUES
(1, '2020-06-14 00:00:00', '2020-12-31 23:59:59', 1, 0, false, 35.50, 'EUR'),
(1, '2020-06-14 15:00:00', '2020-06-14 18:30:00', 2, 1, true, 25.45, 'EUR'),
(1, '2020-06-15 00:00:00', '2020-06-15 11:00:00', 3, 1, false, 30.50, 'EUR'),
(1, '2020-06-15 16:00:00', '2020-12-31 23:59:59', 4, 1, true, 38.95, 'EUR');